#!/bin/bash

#
# Puts the sample component into the development directory.
#
# $1 is the name of the component.
# $2 is the $RESTX_HOME directory
# $3 is the path to the restx_components_list/__init__.py file
#

#
# This is the Java version of the placement script
#

name="$1"
RESTX_HOME="$2"
COMPONENT_LIST="$3"

LANGUAGE="Java"
LANGUAGE_ENDING=".java"
LANGUAGES_SRC="$RESTX_HOME/languages/java/src"
RESTX_SRC="$RESTX_HOME/src/java"
SAMPLE_COMPONENT_NAME="SampleComponent"

"$RESTX_HOME"/bin/generic_placement "$name" "$RESTX_HOME" "$LANGUAGE" "$LANGUAGE_ENDING" "$LANGUAGES_SRC" "$RESTX_SRC" "$SAMPLE_COMPONENT_NAME" "$COMPONENT_LIST" "-" 1

